exports.seed = function (knex) {
    // Deletes ALL existing entries
    return knex('Users')
        .del()
        .then(function () {
            // Inserts seed entries
            return knex('Users').insert([
                {
                    UserKey: 1,
                    UserFirstName: 'Sarvesh',
                    UserLastName: 'Acharya',
                    UserPhone: 1111111111,
                    UserEmail: 'sarveshacharya@live.com',
                    AddressLine1: 'AddressLine1',
                    AddressLine2: 'AddressLine2',
                    City: 'City',
                    State: 'State',
                    Zip: 'Zip',
                    UserIdType: 'UserIdType',
                    UserIdNumber: '2',
                    UserPassword: '$2b$15$PI1ksktG0zGBFxNZkWIcdu2sxLC9F.mM.yKpF/iO6h.kYkdu57wBK',
                    UserCreateTS: new Date(),
                    UserLastUpdatedDateTime: new Date(),
                },
                {
                    UserKey: 2,
                    UserFirstName: 'Manager',
                    UserLastName: 'User',
                    UserPhone: 2222222222,
                    UserEmail: 'manager@email.com',
                    AddressLine1: 'AddressLine1',
                    AddressLine2: 'AddressLine2',
                    City: 'City',
                    State: 'State',
                    Zip: 'Zip',
                    UserIdType: 'UserIdType',
                    UserIdNumber: '2',
                    UserPassword: '$2b$15$PI1ksktG0zGBFxNZkWIcdu2sxLC9F.mM.yKpF/iO6h.kYkdu57wBK',
                    UserCreateTS: new Date(),
                    UserLastUpdatedDateTime: new Date(),
                },
                {
                    UserKey: 3,
                    UserFirstName: 'Cashier',
                    UserLastName: 'User',
                    UserPhone: 3333333333,
                    UserEmail: 'cashier@email.com',
                    AddressLine1: 'AddressLine1',
                    AddressLine2: 'AddressLine2',
                    City: 'City',
                    State: 'State',
                    Zip: 'Zip',
                    UserIdType: 'UserIdType',
                    UserIdNumber: '2',
                    UserPassword: '$2b$15$PI1ksktG0zGBFxNZkWIcdu2sxLC9F.mM.yKpF/iO6h.kYkdu57wBK',
                    UserCreateTS: new Date(),
                    UserLastUpdatedDateTime: new Date(),
                },
                {
                    UserKey: 4,
                    UserFirstName: 'Owner',
                    UserLastName: 'User',
                    UserPhone: 4444444444,
                    UserEmail: 'owner@email.com',
                    AddressLine1: 'AddressLine1',
                    AddressLine2: 'AddressLine2',
                    City: 'City',
                    State: 'State',
                    Zip: 'Zip',
                    UserIdType: 'UserIdType',
                    UserIdNumber: '2',
                    UserPassword: '$2b$15$PI1ksktG0zGBFxNZkWIcdu2sxLC9F.mM.yKpF/iO6h.kYkdu57wBK',
                    UserCreateTS: new Date(),
                    UserLastUpdatedDateTime: new Date(),
                },
                {
                    UserKey: 5,
                    UserFirstName: 'Customer',
                    UserLastName: 'User',
                    UserPhone: 5555555555,
                    UserEmail: 'customer@email.com',
                    AddressLine1: 'AddressLine1',
                    AddressLine2: 'AddressLine2',
                    City: 'City',
                    State: 'State',
                    Zip: 'Zip',
                    UserIdType: 'UserIdType',
                    UserIdNumber: '2',
                    UserPassword: '$2b$15$PI1ksktG0zGBFxNZkWIcdu2sxLC9F.mM.yKpF/iO6h.kYkdu57wBK',
                    UserCreateTS: new Date(),
                    UserLastUpdatedDateTime: new Date(),
                },

                {
                    UserKey: 6,
                    UserFirstName: 'Fulfilment',
                    UserLastName: 'User',
                    UserPhone: 6666666666,
                    UserEmail: 'fulfilment@email.com',
                    AddressLine1: 'AddressLine1',
                    AddressLine2: 'AddressLine2',
                    City: 'City',
                    State: 'State',
                    Zip: 'Zip',
                    UserIdType: 'UserIdType',
                    UserIdNumber: '2',
                    UserPassword: '$2b$15$PI1ksktG0zGBFxNZkWIcdu2sxLC9F.mM.yKpF/iO6h.kYkdu57wBK',
                    UserCreateTS: new Date(),
                    UserLastUpdatedDateTime: new Date(),
                },
            ]);
        });
};
